/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\cargo-carrying_drones.glb 
Author: LaserPigXxx (https://sketchfab.com/LaserPigXxx)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cargo-carrying-drones-6de294e6cd584f6dbf7803b2d418b8ca
Title: Cargo-carrying drones
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/cargo-carrying_drones.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log('Animations:', Object.keys(actions))
    const first = Object.values(actions)[0]
    if (first) {
      first.timeScale = 0.8
      first.play()
    }
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -Math.PI]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_35">
                <group name="bone2_14" position={[0, 0.375, 0.313]}>
                  <group name="cuboid_12" position={[0, -0.125, -0.313]}>
                    <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.material_3} />
                  </group>
                  <group name="cuboid_13" position={[-0.031, 0, -0.688]}>
                    <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material_4} />
                  </group>
                </group>
                <group name="bone_19" position={[0.563, 0, -0.563]}>
                  <group name="plane_15" position={[-0.188, 0.188, 0]}>
                    <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.material_5} />
                  </group>
                  <group name="plane_16" position={[0.188, 0.188, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
                    <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.material_5} />
                  </group>
                  <group name="plane_17" position={[0, 0.188, -0.188]} rotation={[0, -Math.PI / 2, 0]}>
                    <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.material_5} />
                  </group>
                  <group name="plane_18" position={[0, 0.188, 0.188]} rotation={[0, Math.PI / 2, 0]}>
                    <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.material_5} />
                  </group>
                </group>
                <group name="bone3_24" position={[0.563, 0, 0.438]}>
                  <group name="plane_20" position={[-0.188, 0.188, 0]}>
                    <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.material_5} />
                  </group>
                  <group name="plane_21" position={[0.188, 0.188, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
                    <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.material_5} />
                  </group>
                  <group name="plane_22" position={[0, 0.188, -0.188]} rotation={[0, -Math.PI / 2, 0]}>
                    <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.material_5} />
                  </group>
                  <group name="plane_23" position={[0, 0.188, 0.188]} rotation={[0, Math.PI / 2, 0]}>
                    <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.material_5} />
                  </group>
                </group>
                <group name="bone4_29" position={[-0.563, 0, 0.438]}>
                  <group name="plane_25" position={[-0.188, 0.188, 0]}>
                    <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.material_5} />
                  </group>
                  <group name="plane_26" position={[0.188, 0.188, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
                    <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.material_5} />
                  </group>
                  <group name="plane_27" position={[0, 0.188, -0.188]} rotation={[0, -Math.PI / 2, 0]}>
                    <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.material_5} />
                  </group>
                  <group name="plane_28" position={[0, 0.188, 0.188]} rotation={[0, Math.PI / 2, 0]}>
                    <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.material_5} />
                  </group>
                </group>
                <group name="bone5_34" position={[-0.563, 0, -0.5]}>
                  <group name="plane_30" position={[-0.188, 0.188, 0]}>
                    <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material_5} />
                  </group>
                  <group name="plane_31" position={[0.188, 0.188, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
                    <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material_5} />
                  </group>
                  <group name="plane_32" position={[0, 0.188, -0.188]} rotation={[0, -Math.PI / 2, 0]}>
                    <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.material_5} />
                  </group>
                  <group name="plane_33" position={[0, 0.188, 0.188]} rotation={[0, Math.PI / 2, 0]}>
                    <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material_5} />
                  </group>
                </group>
                <group name="cuboid_0" position={[-0.063, 0, 0]}>
                  <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.material_0} />
                </group>
                <group name="cuboid_1" position={[0, -0.125, 0]}>
                  <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.material_1} />
                </group>
                <group name="cuboid_2" position={[0.563, 0, -0.563]}>
                  <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.material_2} />
                </group>
                <group name="cuboid_3" position={[-0.188, 0, 0.063]}>
                  <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.material_0} />
                </group>
                <group name="cuboid_4" position={[-0.438, 0, 0.063]}>
                  <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.material_0} />
                </group>
                <group name="cuboid_5" position={[-0.313, 0, 0]}>
                  <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.material_0} />
                </group>
                <group name="cuboid_6" position={[-0.688, 0, 0.063]}>
                  <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.material_0} />
                </group>
                <group name="cuboid_7" position={[-0.563, 0, 0]}>
                  <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.material_0} />
                </group>
                <group name="cuboid_8" position={[-0.813, 0, 0]}>
                  <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.material_0} />
                </group>
                <group name="cuboid_9" position={[0.563, 0, 0.438]}>
                  <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.material_2} />
                </group>
                <group name="cuboid_10" position={[-0.563, 0, 0.438]}>
                  <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.material_2} />
                </group>
                <group name="cuboid_11" position={[-0.563, 0, -0.5]}>
                  <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.material_2} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/cargo-carrying_drones.glb')
