/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\mailbox.glb 
Author: shalimman (https://sketchfab.com/shalimman)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/mailbox-6fcb00d500aa48a59dd7e8691ba23674
Title: Mailbox
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/mailbox.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Ground.001']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Mailbox} position={[0, 0.2, 0]} scale={0.666} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Ground.001']} position={[0.043, 2.374, 1.072]} rotation={[0.354, -0.312, 0.113]} scale={[0.739, 0.739, 1.366]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Ground.001']} position={[0, 3.5, 0.175]} rotation={[Math.PI / 2, 0, 0]} scale={1.108} />
    </group>
  )
}

useGLTF.preload('/models/mailbox.glb')
