/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 js-logo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/js-logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh.geometry} material={materials.yellow} />
      <mesh geometry={nodes.Mesh_1.geometry} material={materials.black} />
    </group>
  )
}

useGLTF.preload('/models/js-logo.glb')
